In [11]:
import numpy as np

x = np.array([[1, 3, 4], [2, 4, 30]])
print(x)

y= np.array([[1], [3]])
print(y)

[[ 1  3  4]
 [ 2  4 30]]
[[1]
 [3]]


In [5]:
print( x - y)

[[ 0  2  3]
 [-1  1 27]]


In [18]:
print(y)
print(y * np.ones((2,3), int))

[[1]
 [3]]
[[1 1 1]
 [3 3 3]]


In [14]:
y * np.ones()

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [20]:
a = [1, 2, 3, 4, 5, 6, 7]
for item in a[1:7]:
    print(item)


2
3
4
5
6
7
